// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADqA9bjPzE8GcIVT29tJptsCwrkvsQt5U',
    appId: '1:766970406268:web:035a5ead325f88819db0f9',
    messagingSenderId: '766970406268',
    projectId: 'movies-catalog-8a0e9',
    authDomain: 'movies-catalog-8a0e9.firebaseapp.com',
    storageBucket: 'movies-catalog-8a0e9.firebasestorage.app',
    measurementId: 'G-3T6E0ZTFCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvo9e820S_xhup1RVs39WuxPzrL_g1wAA',
    appId: '1:766970406268:android:593b849a81c2a1d59db0f9',
    messagingSenderId: '766970406268',
    projectId: 'movies-catalog-8a0e9',
    storageBucket: 'movies-catalog-8a0e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGbVTwBvkIsuiD_EugUjOC7oW1TFchf10',
    appId: '1:766970406268:ios:2f4c180834f74ac09db0f9',
    messagingSenderId: '766970406268',
    projectId: 'movies-catalog-8a0e9',
    storageBucket: 'movies-catalog-8a0e9.firebasestorage.app',
    iosBundleId: 'com.example.aplicacionesMoviles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGbVTwBvkIsuiD_EugUjOC7oW1TFchf10',
    appId: '1:766970406268:ios:2f4c180834f74ac09db0f9',
    messagingSenderId: '766970406268',
    projectId: 'movies-catalog-8a0e9',
    storageBucket: 'movies-catalog-8a0e9.firebasestorage.app',
    iosBundleId: 'com.example.aplicacionesMoviles',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADqA9bjPzE8GcIVT29tJptsCwrkvsQt5U',
    appId: '1:766970406268:web:52923e99968a37969db0f9',
    messagingSenderId: '766970406268',
    projectId: 'movies-catalog-8a0e9',
    authDomain: 'movies-catalog-8a0e9.firebaseapp.com',
    storageBucket: 'movies-catalog-8a0e9.firebasestorage.app',
    measurementId: 'G-H6LSQECDVD',
  );

}